services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rec
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: