-- =============================================================================
-- Имя модели: rec-db
-- Создано: 11.11.2024 23:51:54
-- Версия модели: 
-- =============================================================================


CREATE TABLE "universyties" (
	"universityID" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" varchar(250) NOT NULL,
	"cityID" int4 NOT NULL,
	PRIMARY KEY("universityID")
);

CREATE TABLE "cities" (
	"cityID" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(250) NOT NULL,
	PRIMARY KEY("cityID")
);

CREATE TABLE "users" (
	"userID" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"cityID" int4 NOT NULL,
	"universityID" int4 NOT NULL,
	"gender" bool,
	"age" int4,
	"params" jsonb,
	PRIMARY KEY("userID")
);

CREATE TABLE "directions" (
	"directionID" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"universityID" int4 NOT NULL,
	"cityID" int4 NOT NULL,
	"code" varchar(255) NOT NULL,
	"name" varchar(250) NOT NULL,
	"params" jsonb,
	"cost" int4,
	PRIMARY KEY("directionID")
);

CREATE TABLE "directionsFeedbacks" (
	"userID" int4 NOT NULL,
	"directionID" int4 NOT NULL,
	"rating" float4 NOT NULL,
	PRIMARY KEY("userID","directionID")
);

CREATE TABLE "universityFeedbacks" (
	"rating" int4,
	"userID" int4 NOT NULL,
	"universityID" int4 NOT NULL
);


ALTER TABLE "universyties" ADD CONSTRAINT "Ref_universyties_to_cities" FOREIGN KEY ("cityID")
	REFERENCES "cities"("cityID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "users" ADD CONSTRAINT "Ref_user_to_cities" FOREIGN KEY ("cityID")
	REFERENCES "cities"("cityID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "users" ADD CONSTRAINT "Ref_user_to_universyties" FOREIGN KEY ("universityID")
	REFERENCES "universyties"("universityID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "directions" ADD CONSTRAINT "Ref_directions_to_universyties" FOREIGN KEY ("universityID")
	REFERENCES "universyties"("universityID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "directions" ADD CONSTRAINT "Ref_directions_to_cities" FOREIGN KEY ("cityID")
	REFERENCES "cities"("cityID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "directionsFeedbacks" ADD CONSTRAINT "Ref_directionsFeedbacks_to_user" FOREIGN KEY ("userID")
	REFERENCES "users"("userID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "directionsFeedbacks" ADD CONSTRAINT "Ref_directionsFeedbacks_to_directions" FOREIGN KEY ("directionID")
	REFERENCES "directions"("directionID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "universityFeedbacks" ADD CONSTRAINT "Ref_universityFeedbacks_to_user" FOREIGN KEY ("userID")
	REFERENCES "users"("userID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "universityFeedbacks" ADD CONSTRAINT "Ref_universityFeedbacks_to_universyties" FOREIGN KEY ("universityID")
	REFERENCES "universyties"("universityID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;


